import type { ThemeConfig } from "antd";
import { theme } from "antd";

const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  "token": {
    "colorPrimary": "#3b82f6",
    "colorSuccess": "#22c55e",
    "colorWarning": "#f97316",
    "colorError": "#ef4444",
    "colorInfo": "#3b82f6",
    "colorTextBase": "#f1f5f9",
    "colorBgBase": "#0f172a",
    "colorPrimaryBg": "#1e293b",
    "colorPrimaryBgHover": "#1e3a8a",
    "colorPrimaryBorder": "#2563eb",
    "colorPrimaryBorderHover": "#3b82f6",
    "colorPrimaryHover": "#2563eb",
    "colorPrimaryActive": "#1d4ed8",
    "colorPrimaryText": "#60a5fa",
    "colorPrimaryTextHover": "#93c5fd",
    "colorPrimaryTextActive": "#dbeafe",
    "colorSuccessBg": "#14532d",
    "colorSuccessBgHover": "#166534",
    "colorSuccessBorder": "#16a34a",
    "colorSuccessBorderHover": "#22c55e",
    "colorSuccessHover": "#16a34a",
    "colorSuccessActive": "#15803d",
    "colorSuccessText": "#4ade80",
    "colorSuccessTextHover": "#86efac",
    "colorSuccessTextActive": "#bbf7d0",
    "colorWarningBg": "#7c2d12",
    "colorWarningBgHover": "#9a3412",
    "colorWarningBorder": "#ea580c",
    "colorWarningBorderHover": "#f97316",
    "colorWarningHover": "#ea580c",
    "colorWarningActive": "#c2410c",
    "colorWarningText": "#fb923c",
    "colorWarningTextHover": "#fdba74",
    "colorWarningTextActive": "#fed7aa",
    "colorErrorBg": "#7f1d1d",
    "colorErrorBgHover": "#991b1b",
    "colorErrorBorder": "#dc2626",
    "colorErrorBorderHover": "#ef4444",
    "colorErrorHover": "#dc2626",
    "colorErrorActive": "#b91c1c",
    "colorErrorText": "#f87171",
    "colorErrorTextHover": "#fca5a5",
    "colorErrorTextActive": "#fecaca",
    "colorInfoBg": "#1e293b",
    "colorInfoBgHover": "#1e3a8a",
    "colorInfoBorder": "#2563eb",
    "colorInfoBorderHover": "#3b82f6",
    "colorInfoHover": "#2563eb",
    "colorInfoActive": "#1d4ed8",
    "colorInfoText": "#60a5fa",
    "colorInfoTextHover": "#93c5fd",
    "colorInfoTextActive": "#dbeafe",
    "colorText": "#f1f5f9",
    "colorTextSecondary": "#cbd5e1",
    "colorTextTertiary": "#94a3b8",
    "colorTextQuaternary": "#64748b",
    "colorTextDisabled": "#475569",
    "colorBgContainer": "#1e293b",
    "colorBgElevated": "#334155",
    "colorBgLayout": "#0f172a",
    "colorBgSpotlight": "rgba(15, 23, 42, 0.95)",
    "colorBgMask": "rgba(0, 0, 0, 0.65)",
    "colorBorder": "#334155",
    "colorBorderSecondary": "#475569"
  },
  components: {
    Button: {
      controlHeight: 40,
      borderRadius: 8,
    },
    Layout: {
      headerBg: "#000000",
    },
    Card: {
      borderRadiusLG: 12,
    },
  },
};

export default darkTheme;
