import type { ThemeConfig } from "antd";
import { theme } from "antd";

const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: "#2563eb",
    colorSuccess: "#16a34a",
    colorWarning: "#ea580c",
    colorError: "#dc2626",
    colorInfo: "#2563eb",
    colorTextBase: "#0f172a",
    colorBgBase: "#ffffff",
    colorPrimaryBg: "#eff6ff",
    colorPrimaryBgHover: "#dbeafe",
    colorPrimaryBorder: "#93c5fd",
    colorPrimaryBorderHover: "#60a5fa",
    colorPrimaryHover: "#3b82f6",
    colorPrimaryActive: "#1d4ed8",
    colorPrimaryText: "#2563eb",
    colorPrimaryTextHover: "#3b82f6",
    colorPrimaryTextActive: "#1d4ed8",
    colorSuccessBg: "#f0fdf4",
    colorSuccessBgHover: "#dcfce7",
    colorSuccessBorder: "#86efac",
    colorSuccessBorderHover: "#4ade80",
    colorSuccessHover: "#22c55e",
    colorSuccessActive: "#15803d",
    colorSuccessText: "#16a34a",
    colorSuccessTextHover: "#22c55e",
    colorSuccessTextActive: "#15803d",
    colorWarningBg: "#fff7ed",
    colorWarningBgHover: "#fed7aa",
    colorWarningBorder: "#fdba74",
    colorWarningBorderHover: "#fb923c",
    colorWarningHover: "#f97316",
    colorWarningActive: "#c2410c",
    colorWarningText: "#ea580c",
    colorWarningTextHover: "#f97316",
    colorWarningTextActive: "#c2410c",
    colorErrorBg: "#fef2f2",
    colorErrorBgHover: "#fecaca",
    colorErrorBorder: "#fca5a5",
    colorErrorBorderHover: "#f87171",
    colorErrorHover: "#ef4444",
    colorErrorActive: "#b91c1c",
    colorErrorText: "#dc2626",
    colorErrorTextHover: "#ef4444",
    colorErrorTextActive: "#b91c1c",
    colorInfoBg: "#eff6ff",
    colorInfoBgHover: "#dbeafe",
    colorInfoBorder: "#93c5fd",
    colorInfoBorderHover: "#60a5fa",
    colorInfoHover: "#3b82f6",
    colorInfoActive: "#1d4ed8",
    colorInfoText: "#2563eb",
    colorInfoTextHover: "#3b82f6",
    colorInfoTextActive: "#1d4ed8",
    colorText: "#1e293b",
    colorTextSecondary: "#475569",
    colorTextTertiary: "#64748b",
    colorTextQuaternary: "#94a3b8",
    colorTextDisabled: "#cbd5e1",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#f8fafc",
    colorBgLayout: "#f1f5f9",
    colorBgSpotlight: "rgba(15, 23, 42, 0.9)",
    colorBgMask: "rgba(15, 23, 42, 0.45)",
    colorBorder: "#e2e8f0",
    colorBorderSecondary: "#f1f5f9",
    borderRadius: 12,
    borderRadiusXS: 4,
    borderRadiusSM: 8,
    borderRadiusLG: 16,
    padding: 20,
    paddingSM: 16,
    paddingLG: 28,
    margin: 20,
    marginSM: 16,
    marginLG: 28,
    boxShadow: "0 4px 12px 0 rgba(15, 23, 42, 0.08)",
    boxShadowSecondary: "0 8px 24px 0 rgba(15, 23, 42, 0.12)",
    fontFamily: "sans-serif",
    fontSize: 15,
    fontSizeSM: 13,
    fontSizeLG: 17,
    lineHeight: 1.6,
    lineHeightLG: 1.75,
  },
  components: {
    Button: {
      controlHeight: 40,
      borderRadius: 8,
    },
    Layout: {
      headerBg: "#ffffff",
    },
    Card: {
      borderRadiusLG: 12,
    },
  },
};

export default lightTheme;
